### ISSUE TITLE
config to reduce loot drop

### ISSUE THREAD

**Issue by Squeetsquib** [ImExoOdeex/SupplementaryAccessories#1]
when can we expect to see a config to reduce loot ?

**Comment by ImExoOdeex** [comment]
In a moment I will release a new version with loot reduced by 50%. I started making config for stopwatch item, but your propostion sounds good! I will try to do it in the next update <3

**Comment by Squeetsquib** [comment]
thanks! Is there config to adjust the loot or just 50% across the board. Was hoping to make them basically non-existent in village chests and only from treasure chests

**Comment by ImExoOdeex** [comment]
hello again, I made config to decrease loot in all and to disable loot in village. Changing these settings requires of course game restart, beacuse loot change is called on Initialize :D
