### ISSUE TITLE
Failed to handle packet for [IP]

### ISSUE THREAD

**Issue by ImExoOdeex** [ImExoOdeex/SupplementaryAccessories#3]
I know the bug with playing on the server, when player equips some items, he is kicked automatically. I'm trying to fix it.
currently is a anit-server bug D;

**Comment by noblereign** [comment]
having this same issue, i was really excited to use this mod but now one of my friends is stuck being kicked from the server over and over again :( pls fix

**Comment by noblereign** [comment]
![image](https://user-images.githubusercontent.com/2935979/170832548-ef5dc775-12ca-4600-a6f1-f000e9232ec4.png)

**Comment by ImExoOdeex** [comment]
Today I should update with fixed version :D

**Comment by ImExoOdeex** [comment]
just released a new version without this but, soo closing
