### ISSUE TITLE
When Balloon/Cloud in a Balloon is held whilst flying in creative mode, the player will move slowly upwards.

### ISSUE THREAD

**Issue by Aquaeyes** [ImExoOdeex/SupplementaryAccessories#5]

**Comment by Aquaeyes** [comment]
Also allows for infinite elytra flight.

**Comment by ImExoOdeex** [comment]
oh I did not take elytra into scope. I think it's very easy to fix. It will be fixed in the next update. Thanks for reporting it

**Comment by ImExoOdeex** [comment]
fixed
