### ISSUE TITLE
Can you add my translation in Simplified Chinese?

### ISSUE THREAD

**Issue by VAN-192** [ImExoOdeex/SupplementaryAccessories#9]
Thank you very much for creating the mod, for which I have created a short Chinese translation and hope it will be adopted.
[zh_cn.txt](https://github.com/ImExoOdeex/Utilities/files/9307731/zh_cn.txt)

**Comment by ImExoOdeex** [comment]
Added in newest version (1.5.4), thanks for supporting <3
